1715687957.708828 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:91 __init__ INFO: Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    executors=(ThreadPoolExecutor(
        label='threads', 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    ),), 
    garbage_collect=True, 
    initialize_logging=True, 
    internal_tasks_max_threads=10, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    retry_handler=None, 
    run_dir='runinfo', 
    std_autopath=None, 
    strategy='simple', 
    strategy_period=5, 
    usage_tracking=False
)
1715687957.709013 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:93 __init__ INFO: Parsl version: 2024.05.13
1715687957.709173 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.usage_tracking.usage:114 __init__ DEBUG: Tracking status: False
1715687957.709634 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.usage_tracking.usage:148 construct_start_message DEBUG: Usage tracking start message: {'correlator': '4db011b0-a74f-4010-abc3-561235de552a', 'parsl_v': '2024.05.13', 'python_v': '3.10.12', 'platform.system': 'Linux', 'start': 1715687957, 'components': [{'c': 'parsl.config.Config', 'executors_len': 1}, 'parsl.executors.threads.ThreadPoolExecutor']}
1715687957.709778 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:121 __init__ INFO: Run id is: 203cf93f-56c2-420b-93ea-b4853d8ae4d4
1715687957.741925 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:128 __init__ DEBUG: Considering candidate for workflow name: /home/srtejaa/.local/lib/python3.10/site-packages/parsl/dataflow/dflow.py
1715687957.742045 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:128 __init__ DEBUG: Considering candidate for workflow name: /home/srtejaa/.local/lib/python3.10/site-packages/parsl/dataflow/dflow.py
1715687957.742122 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:128 __init__ DEBUG: Considering candidate for workflow name: /home/srtejaa/Desktop/2024/Parallel-Programming/Day5/Parsl/./myBash.py
1715687957.742162 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:134 __init__ DEBUG: Using myBash.py as workflow name
1715687957.742311 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.memoization:163 __init__ INFO: App caching initialized
1715687957.742386 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.jobs.strategy:145 __init__ DEBUG: Scaling strategy: simple
1715687957.743966 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:994 submit DEBUG: Task 0 will be sent to executor threads
1715687957.744093 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:787 _add_output_deps DEBUG: Adding output dependencies
1715687957.744184 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:1072 submit INFO: Task 0 submitted for App myFun, not waiting on any dependency
1715687957.744242 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:1078 submit DEBUG: Task 0 set to pending state with AppFuture: <AppFuture at 0x78aab2e6a4a0 state=pending>
1715687957.744298 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.memoization:222 check_memo DEBUG: Task 0 will not be memoized
1715687957.744807 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:745 launch_task INFO: Parsl task 0 try 0 launched on executor threads
1715687957.744914 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:1424 log_std_stream INFO: Standard out for task 0 will be redirected to fileOne.txt
1715687957.745272 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:1424 log_std_stream INFO: Standard error for task 0 will be redirected to fileTwo.txt
1715687957.747606 2024-05-14 17:29:17 MainProcess-78656 ThreadPoolExecutor-0_0-132674530305600 parsl.dataflow.dflow:570 _complete_task INFO: Task 0 completed (launched -> exec_done)
1715687957.747851 2024-05-14 17:29:17 MainProcess-78656 ThreadPoolExecutor-0_0-132674530305600 parsl.dataflow.dflow:1424 log_std_stream INFO: Standard out for task 0 will be redirected to fileOne.txt
1715687957.747970 2024-05-14 17:29:17 MainProcess-78656 ThreadPoolExecutor-0_0-132674530305600 parsl.dataflow.dflow:1424 log_std_stream INFO: Standard error for task 0 will be redirected to fileTwo.txt
1715687957.748343 2024-05-14 17:29:17 MainProcess-78656 MainThread-132674586476992 parsl.dataflow.dflow:1180 atexit_cleanup WARNING: Python is exiting with a DFK still running. You should call parsl.dfk().cleanup() before exiting to release any resources
